# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: a3-ultra-cluster
  namespace: config-control
spec:
  location: us-central1-b
  networkRef:
    name: a3-ultra-vpc
  subnetworkRef:
    name: a3-ultra-subnet
  workloadIdentityConfig:
    workloadPool: "${PROJECT_ID}.svc.id.goog"
  addonsConfig:
    gcsFuseCsiDriverConfig:
      enabled: true
    parallelstoreCsiDriverConfig:
      enabled: true
  masterAuthorizedNetworksConfig:
    cidrBlocks:
      - cidrBlock: "0.0.0.0/0"
        displayName: "kubectl-access-network"
  releaseChannel:
    channel: REGULAR
  ipAllocationPolicy:
    clusterSecondaryRangeName: pods
    servicesSecondaryRangeName: services
  removeDefaultNodePool: true
  initialNodeCount: 1
